experiment:
  id: gen_test_obs6
  stage: 6
  name: "Generalization Test obs=6"

train:
  eval_episodes: 200

env:
  scenario: navigation_obstacle
  num_agents: 4
  num_envs: 1
  num_obstacles: 6
  comm_radius: 0.5
  world_spawning_x: 1.8
  world_spawning_y: 1.8

output:
  category: generalization
  results_dir: results
